import sys
from pathlib import Path

ROOT = Path(r"c:\Users\Ani\OneDrive\Desktop\legal contract Analyzer\rag-legal-contract-analyzer")
sys.path.insert(0, str(ROOT))

from pipeline.document_gate import assess_document

test_text = """
Python Code import numpy as np import matplotlib.pyplot as plt from skimage import data, img_as_float # Load X-ray image (moon surface used as grayscale texture proxy) xray_orig = img_as_float(data.moon()) # Simulate under-exposure: scale pixel intensities to lower range xray_dark = np.clip(xray_orig * 0.28, 0, 1) # Apply logarithmic transformation: T(r) = c * log(1 + r) # c chosen so that maximum output maps to 1.0 c = 1.0 / np.log1p(1.0) log_transformed = c * np.log1p(xray_dark) # Display all three images side-by-side fig, axes = plt.subplots(1, 3, figsize=(15, 5)) for ax, img, title in zip(axes, [xray_orig, xray_dark, log_transformed], ["Original X-ray", "Under-Exposed X-ray", "After Log Transformation"]): ax.imshow(img, cmap='gray', vmin=0, vmax=1) ax.set_title(title); ax.axis('off') plt.tight_layout(); plt.show()
Output Figure 1.1 – Left: original X-ray; Centre: artificially darkened (under-exposed) version; Right: result after log transformation. Analysis & Observations (cid:127) Dynamic Range Compression: The log function maps the compressed low-intensity range of the under-exposed image back to a wider perceptual range, making dark structures visible. (cid:127) Mathematical Basis: T(r) = c·log(1+r), where small r values (dark pixels) receive a proportionally larger boost than bright pixels. (cid:127) Clinical Relevance: In chest X-rays, this technique improves visibility of retrocardiac regions and sub-diaphragmatic structures that are often lost in under-exposure. (cid:127) Limitation: Bright regions (bones) may appear slightly washed out; further gamma adjustment may be needed. Task 2: Histogram Equalization on a Mammogram Objective: Apply histogram equalization to a low-contrast mammogram to redistribute pixel intensities uniformly, improving contrast especially in dense tissue areas.
Python Code from skimage import data, exposure, img_as_float import matplotlib.pyplot as plt
import numpy as np # Load image and simulate low-contrast mammogram raw = img_as_float(data.coins()) mammo = np.clip(raw * 0.45 + 0.05, 0, 1) # narrow dynamic range # Apply global histogram equalization equalized = exposure.equalize_hist(mammo) # Plot images and histograms fig, axes = plt.subplots(2, 3, figsize=(15, 9)) axes[0,0].imshow(mammo, cmap='gray'); axes[0,0].set_title("Original Mammogram") axes[0,1].imshow(equalized, cmap='gray'); axes[0,1].set_title("Equalized Mammogram") axes[1,0].hist(mammo.ravel(), bins=256, color='steelblue') axes[1,1].hist(equalized.ravel(), bins=256, color='darkorange') # CDF comparison for ax, arr, lbl, col in [(axes[1,2], mammo, 'Original', 'steelblue'), (axes[1,2], equalized, 'Equalized', 'darkorange')]: cdf = exposure.cumulative_distribution(arr) ax.plot(cdf[1], cdf[0], label=lbl, color=col) axes[1,2].legend(); plt.tight_layout(); plt.show()
Output Figure 2.1 – Top: before and after equalization; Bottom: histograms and CDF comparison showing the broadened intensity distribution. Analysis & Observations (cid:127) Contrast Improvement: The equalized mammogram shows significantly improved contrast; features that were invisible in the narrow-range original become distinguishable. (cid:127) Uniform Histogram: Post-equalization, pixel intensities are spread across the full [0,1] range, evidenced by the flat histogram. (cid:127) CDF Linearity: The equalized CDF closely follows a straight diagonal line, confirming successful equalization. (cid:127) Clinical Application: Improved contrast aids radiologists in detecting micro-calcifications and boundary irregularities in dense breast tissue. (cid:127) Limitation: Global equalization may over-amplify noise in homogeneous regions; CLAHE (Contrast-Limited Adaptive Histogram Equalization) is preferred clinically. Task 3: Mean vs Median Filtering on a Noisy CT Image Objective: Add Gaussian noise to a CT image and compare the denoising performance of mean (average) and median filters, with particular attention to edge preservation.
"""

is_contract, msg = assess_document(test_text)
print(f"Is Contract: {is_contract}")
print(f"Message: {msg}")
