"""
scripts/sync_docs.py
====================
Compiles project context, handoff status, and evaluation results into a single
unified 'source_of_truth.md' document in the docs/ folder.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "docs"

def main():
    DOCS_DIR.mkdir(exist_ok=True)
    out_path = DOCS_DIR / "source_of_truth.md"
    
    # 1. Read README.md
    readme_path = ROOT / "README.md"
    readme_content = readme_path.read_text(encoding="utf-8") if readme_path.exists() else "No README found."
    
    # 2. Read HANDOFF.md
    handoff_path = ROOT / "HANDOFF.md"
    handoff_content = handoff_path.read_text(encoding="utf-8") if handoff_path.exists() else "No HANDOFF found."
    
    # 3. Read Classifier Report
    report_path = ROOT / "evaluation" / "results" / "classifier_report.json"
    report_text = "No classifier report found."
    if report_path.exists():
        try:
            report_data = json.loads(report_path.read_text(encoding="utf-8"))
            acc = report_data.get("accuracy", 0.0)
            mode = report_data.get("mode", "unknown")
            report_text = f"**Mode:** {mode}\n**Accuracy:** {acc:.1%}\n\n```json\n{json.dumps(report_data, indent=2)}\n```"
        except Exception as e:
            report_text = f"Error reading report: {e}"

    # Build the document
    compiled = f"""# Legal Contract Analyzer — Source of Truth

This document is automatically generated by `scripts/sync_docs.py`. It unifies the project's core documentation and latest evaluation results.

---

## 1. Project Overview (from README.md)

{readme_content}

---

## 2. Status & Next Steps (from HANDOFF.md)

{handoff_content}

---

## 3. Latest Model Evaluation (classifier_report.json)

{report_text}
"""

    out_path.write_text(compiled, encoding="utf-8")
    print(f"Successfully synced docs to {out_path}")

if __name__ == "__main__":
    main()
